name: Backend and integration tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Install firebase tools
        run: yarn add firebase-tools

      - name: Start API
        run: yarn start:api:dev &

      - name: Authenticate with Firebase CLI
        uses: firebase/firebase-actions/setup-firebase@v2
        with:
          firebase-version: '9.x.x'
        env:
          FIREBASE_CLI_TOKEN: development

      - name: Install Firebase CLI
        uses: firebase/firebase-actions/setup-firebase@v2
        with:
          firebase-version: '9.x.x'
        env:
          FIREBASE_CLI_TOKEN: development

      - name: Wait for Api
        run: sleep 60

      - name: Start Emulators
        run: yarn start:emulators:imported &

      - name: Wait for services to start
        run: sleep 360

      - name: Run tests
        run: yarn test:api
