name: Backend and integration tests
on: push
env:
  FIREBASE_PROJECT_ID: demo-project
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Install firebase tools
        run: yarn add firebase-tools

      - name: Authenticate Firebase CLI
        run: firebase login --no-localhost --token "${FIREBASE_TOKEN}"

      - name: Start API
        run: yarn start:api:dev &

      - name: Wait for Api
        run: sleep 60

      - name: Start Emulators
        run: yarn start:emulators:imported &

      - name: Wait for services to start
        run: sleep 360

      - name: Run tests
        run: yarn test:api
