name: Backend and integration tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Start API
        run: yarn start:api:dev
        background: true

      - name: Start Emulators
        run: yarn start:emulators:imported
        background: true

      - name: Wait for services to start
        run: sleep 240

      - name: Run tests
        run: yarn test:api
