name: Jest Front-End Unit Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps for action
      - name: Install Dependencies
        run: yarn install

      # Install Nx
      - name: Install Dependencies
        run: yarn add nx

      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test-user-data-access
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-user-data-access
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-dashboard-feature
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-user-feature
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-user-util
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-feed
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-forgot-feature
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-profile-view
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-search-page
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-search-results
      # Finally, run our tests
      - name: run Unit tests
        run: yarn nx test app-shared
